# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-15 21:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20180915_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='district',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='area',
            field=models.CharField(default='', max_length=100, verbose_name='区'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='市'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='province',
            field=models.CharField(default='', max_length=100, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
    ]
