# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-15 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20180911_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='是否热销', verbose_name='是否热销'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(help_text='商品名', max_length=240, verbose_name='商品名'),
        ),
    ]
