# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-17 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20180917_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='添加时间', verbose_name='添加时间'),
        ),
    ]
