# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-15 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180914_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='phone',
            field=models.CharField(help_text='用户电话', max_length=11, verbose_name='电话'),
        ),
    ]
